# Generated by Django 4.1 on 2022-08-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_date',
            field=models.DateField(auto_now_add=True, verbose_name='RegistrationDate'),
        ),
    ]
