# Generated by Django 4.1 on 2022-08-29 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='student',
            name='registrationDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Registration Date'),
            preserve_default=False,
        ),
    ]
